<?php
// Server configuration
$server["address"]="irc.freenode.net";
$server["port"]="6667";
$server["password"]="";

// Bot information configuration
$user["nick"]="gluxonbot";
$user["mode"]="gluxon.com";
$user["unused"]="unused";
$user["realname"]="sherly";
$user["password"]="";

// Default join channel
$channel["name"]="#gluxon";

// Admins array
$admins = array("~gluxon@unaffiliated/gluxon");
?>
