<?php
// Server configuration
$server["address"]="irc.esper.net";
$server["port"]="6667";
$server["password"]="";

// Bot information configuration
$user["nick"]="AbigailBot";
$user["mode"]="brocrafting.net";
$user["unused"]="unused";
$user["realname"]="Abigail by BroDev";
$user["password"]="";

// Default join channel
$channel["name"]="#BroCrafting";

// Admins array
$admins = array("~user@hostname.net");
?>
