<?php
// Server configuration
$server["address"]="irc.esper.net";
$server["port"]="6667";
$server["password"]="";

// Bot information configuration
$user["nick"]="Syntax";
$user["mode"]="liamstanley.net";
$user["unused"]="unused";
$user["realname"]="Syntax by Liam Stanley";
$user["password"]="";

// Default join channel
$channel["name"]="#L";

// Admins array
$admins = array("~user@hostname.net");
?>
